### ISSUE TITLE
CloudQuery Collaboration?

### ISSUE THREAD

**Issue by yevgenypats** [PaloAltoNetworks/prisma_channel_resources#24]
Hi Team,

Hopefully the right place to reach out. We are working with number of CSPM vendor to migrate their internal ELT engine to sync/fetch resources from AWS, GCP, Azure and other to our open source engine high performance ELT framework - [CloudQuery](https://github.com/cloudquery/cloudquery). Curious if this is something that might be interesting for you. If yes, would love to chat, feel free to ping me at `yp` at `cloudquery.io` or here.

Best,
Yevgeny Pats, Founder @ CloudQuery

**Comment by kyle9021** [comment]
Cheers on that Yevgeny!

Interesting thought and approach.
