### ISSUE TITLE
Download the lab deployment files 

### ISSUE THREAD

**Issue by byronjwatson** [PaloAltoNetworks/prisma_channel_resources#6]
## Documentation link

https://github.com/PaloAltoNetworks/prisma_channel_resources/tree/main/lab_deploy

## Describe the problem

For step 3 of the lab setup, the file location was updated from - 

https://github.com/paloaltonetworks/prisma_partner_resources

to -

https:://github.com/PaloAltoNetworks/prisma_channel_resources

## Suggested fix

cd $HOME
git clone https://github.com/PaloAltoNetworks/prisma_channel_resources
cd prisma_channel_resources/lab_deploy/compose_deploy/

**Comment by kyle9021** [comment]
Great catch.
